### PR TITLE
Rust language support

### PR DESCRIPTION
**Pull request by pthariensflame**
`pythontex` gains it’s first compiled language!  (If this pull request is acceptable.)

### CODE REVIEW

**Comment by gpoore** [comment]
Thanks for this! I've been hoping to add a compiled language, and Rust was a top candidate.

I revised a few things, mostly to make things more similar to other languages. I made most fields of `RustTeXUtils` public and removed the associated `fn`'s, added `#![allow(unused_imports)]`, and made a few other changes. If there's any of that you think should be changed back to the original way, or another way, let me know...I've played with Rust a little, but have minimal experience. No support for encodings other than UTF8 shouldn't be an issue. Using `*.exe` for everything is fine for now. I plan to add support for system-specific commands soon.

I think this should be very usable as-is. However, in the future, I expect it may be worth revisiting the handling of `formatter()`, `before()`, and `after()`. But that can wait until more people have tried it.

I'd like to add you to the acknowledgements. Also, I'd be interested in any comments you have about the general system for adding languages. I'm working on migrating over to a system in which all the language templates, commands, etc. are in config files instead of a Python script (support for multiple formats; JSON, YAML, maybe TOML, etc.). That should simplify things.

**Comment by pthariensflame** [comment]
@gpoore I would be honored to have a place in the acknowledgements.  ❤️ 

As for the system for adding languages, it seems fairly good right now (if rather imperative-specific; I tried to add Haskell support before switching over to Rust, and it was just impossible to fulfill the stated requirements—but I don't have any ideas on how to fix that, so the point is kind of moot).  Config files might make the process even easier, but not by a huge amount.

**Comment by pthariensflame** [comment]
I do have some ideas for improving the Rust support even further; I'll submit another pull request with those soon.

**Comment by gpoore** [comment]
More improvements sound good. I'll look forward to seeing those when you have them.

In terms of limitations of the current language system: Currently, each chunk of code is put into a wrapper template. This is necessary for capturing and syncing stdout and stderr, but I plan to add an option eventually that makes this optional, so that it's possible to add chunks of code that aren't modified in any way. That would make it possible in the Rust case to have code outside of `main()` (though having everything in `main()` seems like a sensible default). That would also make it possible to split, say, a function definition over multiple environments.

**Pull request closed without merging**
