### PR TITLE
Tab support

### PR DESCRIPTION
**Pull request by FedorSarafanov**
This code added "tabulation support". If user have in pycode environment tab align all lines of code, for example:
```
\begin{pycode}
	   import numpy as np
	   x=np.linspace(0,10,100)
	   y=np.cos(x)
	   def draw(x,y,param='black'):
		   s=''
		   for i in range(0,len(x)):
 			   s+=' (%s,%s)'%(x[i],y[i])
		   return str(r'\draw plot[%s] coordinates{%s};'%(param,s))
\end{pycode}
```

It's really convenient for those who are interested in the beauty of the tabulation code.

Note: this code only for tab (not spaces), and python code in pycode environments required first line as filled of user python code (
as in the example above).

This is still a very weak code, but I want you to fully implement this feature. Sorry, I'm a physicist, not a programmer)

### CODE REVIEW

**Comment by FedorSarafanov** [comment]
Of course.

Suppose I want to compile this code:

```
\documentclass[tikz,border=2mm]{standalone}
\usepackage{pythontex}

\begin{document}
	\begin{tikzpicture}

		\begin{pycode}
			import numpy as np
			from numpy import cos,sin,pi

			def draw(x,y,param='black'):
				s=''
				for i in range(0,len(x)):
					s+=' (%s,%s)'%(x[i],y[i])
				return str(r'\draw[%s] plot coordinates{%s};'%(param,s))
			x=np.linspace(-3,3,100)
			y=np.tanh(x)
		\end{pycode}

		\py{draw(x,y)};
		
	\end{tikzpicture}
\end{document}
```

PythonTeX will return an error:

```
----  Messages for py:default:default  ----
* PythonTeX stderr - error on line 9:
    File "<outputdir>\py_default_default.py", line 51
      import numpy as np
      ^
  IndentationError: unexpected indent
```

Obviously, this was due to the fact that the blocks of latex code are aligned with tabulation, and pythontex believes that these tabulations are part of the code on python.

My idea is to count the number of tabs before the beginning of the code in each block of the code, and cut them from the subsequent lines.

Then, regardless of how tab-shifted the environment is, the code will compile.

I know the following problems of my code:

1. It works only for tabulation, but not for quadruple spaces.
2. It works only if the Python code begins with the first line in the environment.

I roughly imagine how this can be fixed, but it seems to me that you will do it better.

P.S. Sorry for my English through Google translator)

**Comment by FedorSarafanov** [comment]
For the same piece of code, pythontex with my edit will work like this:
```
$ pythontex example.py.tex
This is PythonTeX 0.17dev
coun 3
coun 0

--------------------------------------------------
PythonTeX:  example.py - 0 error(s), 0 warning(s)
```

It can be seen that my code found three tabs for the first piece of python code and cut them out, and the error disappeared.


The variable coun (counter of tabulations) in the code is debug, and I print it only to check my code.

**Comment by gpoore** [comment]
Thanks for the examples. That clarifies things. What you want is already possible with the package option `gobble=auto`. Try
```latex
\usepackage[gobble=auto]{pythontex}
```
This only works if the first line of Python code in an environment is not supposed to have any indentation, but that limitation is due to how LaTeX functions rather than anything in PythonTeX.

**Comment by FedorSarafanov** [comment]
Thanks for the answer. I was inattentive when I read the documentation.

Maybe it is worth including this parameter by default? It expands the functionality.

Starting the first time pythonytex, I expected this behavior (as with the parameter gobble = auto) by default.

**Comment by gpoore** [comment]
Don't worry about not seeing the feature in the documentation...there's a lot of documentation.

Using this by default isn't possible, because that would assume that the code inside an environment never has any overall indentation that should be kept. Unfortunately, it isn't possible to deal with this in a way that would meet everyone's LaTeX expectations. It looks like you indent each environment by 1 tab. Some people indent by 4 spaces or 2 spaces instead. Others never indent environments under any circumstances.

**Comment by vcfalk** [comment]
Hi all,

had the same prob that Fedor had some time ago after I copied a snippet of the pythontex gallery.tex file
into a test file within TEXSTUDIO, resulting in TABbed text setting: 

.....
\begin{sympyblock}
	var('x, y, z')
	z = x + y
\end{sympyblock}
...

After I read this actual issue I tried to include

\usepackage[gobble=auto]{pythontex}

but this threw the following error:

....
! LaTeX Error: Option clash for package pythontex.
....

Unfortunately there was no further hint what clashed in detail etc. to trap it down
(I assume its sth about the pgf package?!?)

Any hint fore solution kindly appreciated.

Take care all and stay healthy - Volker

**Pull request closed without merging**
